### ISSUE TITLE
Price Filter Feature

### ISSUE THREAD

**Issue by aviezab** [hfahmi/edulux#24]
![price_filter](https://user-images.githubusercontent.com/34294278/35253467-2a022386-0018-11e8-9b03-afa17387300d.png)

**Comment by shepilov-vladislav** [comment]
Done.

Addon placed here git-edulux:private/odoo/website_price_filter

<img width="1675" alt="shop___website_localhost" src="https://user-images.githubusercontent.com/15679834/35425889-a93c6568-026f-11e8-81d6-3df08a5f3763.png">

**Comment by dozymoe** [comment]
For this we are going to be using the built-in filter-by-price from the theme.

There will probably be more issues, like setting the price value with slider is awkward, and why no filter in "All Products", and why it didn't use ajax.
