### ISSUE TITLE
Bugfix in double shipment methods and UOM at /shop/confirmation/

### ISSUE THREAD

**Issue by aviezab** [hfahmi/edulux#34]
![image](https://user-images.githubusercontent.com/34294278/35868119-35dc0d08-0b8e-11e8-99bc-a11e47cd17bf.png)

**Comment by aviezab** [comment]
"Unit unit" now fixed
Edited website_sale/template.xml : 
Removed product.uom in <div id="quote_qty"> and added "unit" in simpler way.

![image](https://user-images.githubusercontent.com/34294278/35868336-c62a52ca-0b8e-11e8-95a0-c76e40c2f4e8.png)

**Comment by dozymoe** [comment]
This has been fixed by patching odoo's website_sale_delivery.
