### ISSUE TITLE
Invoice Billing Document

### ISSUE THREAD

**Issue by dozymoe** [hfahmi/edulux#9]
> dokumen penagihan invoice

-- Todo Napitupulu

Setelah disetujui di SNAP-nya Midtrans, pembeli dapat salinan invoice lewat email.

Translation:
> Invoice BIlling Document
After approval by SNAP in Midtrans, buyer is able to get copy of purchase invoice via Email.

**Comment by dozymoe** [comment]
For this issue, install odoo_marketplace and payment_midtrans (Payment Acquirer)

Set the following at Website Admin - eCommerce - Payment Acquirers

    Environment: Testing
    Merchant ID: M112885
    Client Key: SB-Mid-client-f0hfGJl5Bfa3Qr5n
    Server Key: SB-Mid-server-hozsfibAbQfYtERtef9j5hvA

Their testing credentials: https://snap-docs.midtrans.com/#testing-credentials

We use SaleOrder id (??) as identifier to midtrans's requests, they are not reusable, for example, since I already used SO0001, you'd get javascript alert saying that order_id was already registered.

Easier if you modified payment_midtrans/models/payment.py line 49:

    values['order'] = request.website.sale_get_order()

into:

    values['order'] = 'VLAD_' + request.website.sale_get_order()

and payment_midtrans/static/src/js/main.js line 104, 116, 128:

    reference: result.order_id,

into:

    reference: result.order_id.substr(5),

At payment_midtrans/controllers/main.py line 281 when the SaleOrder `state` is set to "done" or "pending", we want to send a copy of the invoice to the buyer, but only send them once (??).

We don't want to spam the buyer email client with multiple notification callbacks from midtrans api.

This could be done with odoo Server Actions I think, not sure.

I did a post-save Server Actions, see rajaongkir/data/credential.xml

I don't think this is possible for anonymous user, only for registered buyer (a subclass of Partner), so only send for registered buyer.

If you could push a workflow that involves anonymous buyer, where they input their email, that would be great, I imagine this is going to add some difficulties when rendering the email template.

**Comment by shepilov-vladislav** [comment]
Your solution for test way not work. I use this way.

```
def wrap_reference(reference):
    return 'VLAD_' + reference


def unwrap_reference(reference):
    return reference[5:]

```
in `payment_midtrans/controllers/main.py`

and change `reference = post.get('reference')` -> `reference = wrap_reference(post.get('reference'))` for `get_token` and change `reference = post.get('reference')` -> `reference = unwrap_reference(post.get('reference'))` for `payment_validate` and `midtrans_notification`.

**Comment by shepilov-vladislav** [comment]
Done.

Addon placed here: git-edulux:private/odoo/payment_midtrans_auto_quatation
Required changes from branch issue_9 from repo git-edulux:private/odoo/payment_midtrans

**Comment by dozymoe** [comment]
I am merging payment_midtrans_auto_quatation to payment_midtrans reason being I don't like that the ORM Environment.context was not stored in inter-process storage, actually it shouldn't be a problem because the notification callback from Midtrans and the one sending the email is the same odoo server.

Personal preference I guess.

Also created new issue #25, the bug happens both when the code is in separate module and after it had been merge to payment_midtrans
